### ISSUE TITLE
Add SD-card access

### ISSUE THREAD

**Issue by xfjx** [tonuino/TonUINO-TNG#8]
via admin menu and/or via special card

**Comment by seisfeld** [comment]
It should be discussed wether this should be included in the enduser firmware (due to extensive test requirements regarding "what happens to the FAT of the sd card when files and/or folders get deleted and added") or reserved for a special debug firmware (to read out the version of the player firmware or update the player firmware for example). Sequential playback could be affected on some if not all player chips on the AiO / AiO Plus.

**Comment by boerge1** [comment]
@seisfeld Better to close this as "not planed" and not as "completed"
